import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** Positivus-inspired — dark surfaces + neon lime accent */
export default {
  darkMode: "class",
  content: ["./*.html", "./scripts/**/*.js", "./src/**/*.js"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#F3F3F3",
        "primary-container": "#B9FF66",
        "surface-tint": "#B9FF66",
        "on-tertiary": "#191A23",
        "inverse-surface": "#F3F3F3",
        "on-tertiary-container": "#191A23",
        "on-secondary": "#191A23",
        "on-surface-variant": "#A8A8B3",
        "on-primary-fixed": "#191A23",
        outline: "#8A8A96",
        surface: "#23242F",
        "on-primary-fixed-variant": "#191A23",
        "secondary-container": "#0F1015",
        "on-tertiary-fixed": "#191A23",
        "secondary-fixed": "#2F303C",
        "on-tertiary-fixed-variant": "#191A23",
        "inverse-primary": "#B9FF66",
        "tertiary-fixed-dim": "#7CB342",
        "outline-variant": "#3D3E4A",
        "primary-fixed": "#B9FF66",
        background: "#191A23",
        error: "#FF6B6B",
        "on-primary-container": "#191A23",
        secondary: "#B9FF66",
        "surface-container-low": "#1E1F28",
        "on-background": "#F3F3F3",
        "on-error": "#FFFFFF",
        "surface-bright": "#2A2B36",
        "primary-fixed-dim": "#7CB342",
        "surface-variant": "#2F303C",
        "surface-container-high": "#2A2B36",
        "error-container": "#3D2020",
        "surface-container": "#23242F",
        "secondary-fixed-dim": "#3D3E4A",
        "on-secondary-fixed": "#F3F3F3",
        "inverse-on-surface": "#191A23",
        tertiary: "#7CB342",
        "on-secondary-container": "#C8C8D0",
        "surface-container-lowest": "#14151C",
        primary: "#B9FF66",
        "on-secondary-fixed-variant": "#A8A8B3",
        "on-primary": "#191A23",
        "surface-container-highest": "#353642",
        "on-error-container": "#FFB4AB",
        "surface-dim": "#14151C",
        "tertiary-container": "#B9FF66",
        "tertiary-fixed": "#B9FF66",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "24px",
        sm: "16px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        xl: "64px",
        xs: "8px",
        lg: "40px",
        base: "4px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "data-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "data-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-lg": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
